# Use Node.js 20 as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app/notification

# Copy package.json to the working directory
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Compile TypeScript to JavaScript
RUN npm run build

# Command to run the application
CMD ["node", "dist/notification.js"]